//
//  OnbordingPresenter.swift
//  OlympIt
//
//  Created Nariman on 18.02.2024.
//  Copyright © 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Dastan Makhutov @mchutov
//

import UIKit

final class OnbordingPresenter: OnbordingPresenterProtocol {
    weak private var view: OnbordingViewProtocol?
    var interactor: OnbordingInteractorProtocol?
    private let router: OnbordingWireframeProtocol

    init(interface: OnbordingViewProtocol, interactor: OnbordingInteractorProtocol?, router: OnbordingWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
}
