//
//  OnbordingProtocols.swift
//  OlympIt
//
//  Created Nariman on 18.02.2024.
//  Copyright © 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Dastan Makhutov @mchutov
//

import Foundation

//MARK: Wireframe -
protocol OnbordingWireframeProtocol: AnyObject {

}
//MARK: Presenter -
protocol OnbordingPresenterProtocol: AnyObject {

}

//MARK: Interactor -
protocol OnbordingInteractorProtocol: AnyObject {
  var presenter: OnbordingPresenterProtocol?  { get set }
}

//MARK: View -
protocol OnbordingViewProtocol: AnyObject {
  var presenter: OnbordingPresenterProtocol?  { get set }
}
