//
//  OnbordingViewController.swift
//  OlympIt
//
//  Created Nariman on 18.02.2024.
//  Copyright © 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Dastan Makhutov @mchutov
//

import UIKit

final class OnbordingViewController: UIViewController, OnbordingViewProtocol {
	var presenter: OnbordingPresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
    }
}
