//
//  LessonsListPresenter.swift
//  OlympIt
//
//  Created Nariman on 08.05.2024.
//  Copyright © 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Dastan Makhutov @mchutov
//

import UIKit

final class LessonsListPresenter: LessonsListPresenterProtocol {
    
    weak private var view: LessonsListViewProtocol?
    var interactor: LessonsListInteractorProtocol?
    private let router: LessonsListWireframeProtocol
    private let lessonId: String
    private let type: LessonType
    private let initialLessonType: InitialLessonType
    var lessons: LessonsListOutput = [] {
        didSet {
            view?.reload()
        }
    }

    init(interface: LessonsListViewProtocol, interactor: LessonsListInteractorProtocol?, router: LessonsListWireframeProtocol, initialLessonType: InitialLessonType, type: LessonType, lessonId: String) {
        self.view = interface
        self.interactor = interactor
        self.router = router
        self.lessonId = lessonId
        self.type = type
        self.initialLessonType = initialLessonType
    }
    
    func viewDidLoad() {
        interactor?.fetchLessonsList(initialLessonType: initialLessonType, type: type, id: lessonId)
    }
    
    func didFetchLessons(response: LessonsListOutput) {
        lessons = response
    }
}
