input_dir: ${PROJECT_DIR}/OlympIt
output_dir: ${PROJECT_DIR}/OlympIt/SwiftGen
xcassets:
  inputs:
    - Resources/Assets.xcassets
    - Resources/Colors.xcassets
  outputs:
    - templatePath: ${PROJECT_DIR}/OlympIt/SwiftGen/template.stencil
      params:
        publicAccess: true
      output: Assets.generated.swift
