//
//  NewsListViewController.swift
//  OlympIt
//
//  Created Nariman on 11.05.2024.
//  Copyright © 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Dastan Makhutov @mchutov
//

import UIKit

final class NewsListViewController: UIViewController, NewsListViewProtocol {
	var presenter: NewsListPresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
    }
}
