//
//  NewsListProtocols.swift
//  OlympIt
//
//  Created Nariman on 11.05.2024.
//  Copyright © 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Dastan Makhutov @mchutov
//

import Foundation

//MARK: Wireframe -
protocol NewsListWireframeProtocol: AnyObject {

}
//MARK: Presenter -
protocol NewsListPresenterProtocol: AnyObject {

}

//MARK: Interactor -
protocol NewsListInteractorProtocol: AnyObject {
  var presenter: NewsListPresenterProtocol?  { get set }
}

//MARK: View -
protocol NewsListViewProtocol: AnyObject {
  var presenter: NewsListPresenterProtocol?  { get set }
}
