//
//  DashboardInteractor.swift
//  OlympIt
//
//  Created Nariman on 18.02.2024.
//  Copyright © 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Dastan Makhutov @mchutov
//

import UIKit

final class DashboardInteractor {
    weak var presenter: DashboardPresenterProtocol?
    private let lessonService: LessonService = .init()
}

extension DashboardInteractor: DashboardInteractorProtocol {
    func fetchLesson(with type: LessonType) {
        lessonService.getLessonsList(with: type) { result in
            switch result {
            case .success(let response):
                self.presenter?.didFetchLessons(with: response)
            case .failure(let error):
                self.presenter?.error(message: error.localizedDescription)
            }
        }
    }
}
