//
//  DashboardProtocols.swift
//  OlympIt
//
//  Created Nariman on 18.02.2024.
//  Copyright © 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Dastan Makhutov @mchutov
//

import Foundation

//MARK: Wireframe -
protocol DashboardWireframeProtocol: AnyObject {

}
//MARK: Presenter -
protocol DashboardPresenterProtocol: AnyObject {
    func viewDidLoad()
    
    var examLessons: ExamList { get set }
    var olympLessons: LessonsBaseList { get set }
    var currentLessonType: LessonType { get set }
    
    func didFetchLessons(with lessons: ExamList)
    
    func error(message: String)
}

//MARK: Interactor -
protocol DashboardInteractorProtocol: AnyObject {
    var presenter: DashboardPresenterProtocol?  { get set }
    func fetchExams()
}

//MARK: View -
protocol DashboardViewProtocol: AnyObject,
                                LoadableViewController {
    var presenter: DashboardPresenterProtocol?  { get set }
    func reloadData()
    func showAlert(message: String)
}
