//
//  DashboardPresenter.swift
//  OlympIt
//
//  Created Nariman on 18.02.2024.
//  Copyright © 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Dastan Makhutov @mchutov
//

import UIKit

final class DashboardPresenter {
    weak private var view: DashboardViewProtocol?
    var interactor: DashboardInteractorProtocol?
    private let router: DashboardWireframeProtocol
    
    var examLessons: ExamList = []
    var olympLessons: LessonsBaseList = []
    var currentLessonType: LessonType = .olymp {
        didSet {
            switch currentLessonType {
            case .olymp:
                fetchOlymp()
            case .exam:
                fetchExam()
            }
        }
    }

    init(interface: DashboardViewProtocol, interactor: DashboardInteractorProtocol?, router: DashboardWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
}

extension DashboardPresenter: DashboardPresenterProtocol {
    func viewDidLoad() {
        fetchOlymp()
    }
    
    func didFetchLessons(with lessons: ExamList) {
        switch currentLessonType {
        case .exam:
            examLessons = lessons
        case .olymp: break
//            olympLessons = lessons
        }
        view?.reloadData()
    }
    
    func error(message: String) {
        view?.showAlert(message: message)
    }
}

private extension DashboardPresenter {
    func fetchExam() {
        interactor?.fetchExams()
    }
    
    func fetchOlymp() {
        
    }
}
