//
//  DashboardRouter.swift
//  OlympIt
//
//  Created Nariman on 18.02.2024.
//  Copyright © 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Dastan Makhutov @mchutov
//

import UIKit

final class DashboardRouter: DashboardWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static func createModule() -> UIViewController {
        let view = DashboardViewController()
        let interactor = DashboardInteractor()
        let router = DashboardRouter()
        let presenter = DashboardPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
    
    func openBottomSheet(executor: AnyObject) {
        let vc = SelectableBottomSheet(delegate: executor)
        let nav = UINavigationController(rootViewController: vc)
        nav.modalPresentationStyle = .pageSheet
        
        if let sheet = nav.sheetPresentationController {
            sheet.detents = [.medium()]
        }
        
        viewController?.present(nav, animated: true)
    }
    
    func openLessonsList(initialLessonType: InitialLessonType,type: LessonType, lessonId: String) {
        let vc = LessonsListRouter.createModule(initialLessonType: initialLessonType, type: type, lessonId: lessonId)
        viewController?.dismiss(animated: true)
        viewController?.navigationController?.pushViewController(vc, animated: true)
    }
    
}
