//
//  DashboardViewController.swift
//  OlympIt
//
//  Created Nariman on 18.02.2024.
//  Copyright © 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Dastan Makhutov @mchutov
//

import UIKit

final class DashboardViewController: UIViewController, 
                                     DashboardViewProtocol,
                                     LoadableViewController {
    
	var presenter: DashboardPresenterProtocol?
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        setupNavigationBar()
    }

	override func viewDidLoad() {
        super.viewDidLoad()
        view.backgroundColor = .main404043
    }
}

// MARK: Setup UI
extension DashboardViewController {
    
    private func setupNavigationBar() {
        setLeftAlignedNavigationItemTitle(
            text: "Добро пожаловать",
            color: .white
        )
    }
    
    func setupUI() {
        
    }
    
}
